// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetWalletInfo implements getWalletInfo operation.
	//
	// GET /wallet/{address}
	GetWalletInfo(ctx context.Context, params GetWalletInfoParams) (*WalletInfo, error)
	// GetWallets implements getWallets operation.
	//
	// GET /wallets
	GetWallets(ctx context.Context, params GetWalletsParams) (*WalletList, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
